### ISSUE TITLE
Clarify code

### ISSUE THREAD

**Issue by alax99** [zixuan75/react-project#25]
We need to clarify our code because many code are unclear and do not mean some specific property in our React lines of Code.

- [x] Delete old separators
- [x] Use clear arrow functions instead of old onClick events
- [x] Add marks to tell which is which

**Comment by zixuan75** [comment]
Exactly.

**Comment by zixuan75** [comment]
Complete.

**Comment by zixuan75** [comment]
No comments allowed here anymore.

This project is done.

**Comment by zixuan75** [comment]
Collaborators, done.
